import React from 'react';
import { motion } from 'framer-motion';
import { Info } from 'lucide-react';

const DisclaimerCard: React.FC = () => {
  return (
    <motion.div
      initial={{ y: 30, opacity: 0 }}
      animate={{ y: 0, opacity: 1 }}
      transition={{ duration: 0.6, delay: 0.4 }}
    >
      <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-lg">
        <div className="flex items-start">
          <div className="bg-blue-100 p-2 rounded-lg mr-4 flex-shrink-0">
            <Info className="w-5 h-5 text-blue-600" />
          </div>
          <div>
            <h3 className="text-lg font-semibold text-gray-900 mb-2">Important Disclaimer</h3>
            <div className="text-gray-600 text-sm space-y-2">
              <p>
                This report is generated by AI analysis and should be used as a supplementary tool for assessment. 
                The analysis is based on the responses provided during the interview session.
              </p>
              <p>
                <strong>Please note:</strong> AI analysis may not capture all nuances of human communication and should 
                be considered alongside other evaluation methods for comprehensive assessment.
              </p>
              <p>
                For the most accurate evaluation, combine this report with human judgment and additional assessment criteria 
                relevant to your specific requirements.
              </p>
            </div>
          </div>
        </div>
      </div>
    </motion.div>
  );
};

export default DisclaimerCard;
