import React from 'react';
import { motion } from 'framer-motion';
import { Brain, Mic, FileText, BarChart3 } from 'lucide-react';
import Card from '../Card/Card';

interface Feature {
  icon: React.ReactNode;
  title: string;
  description: string;
}

const FeaturesSection: React.FC = () => {
  const features: Feature[] = [
    {
      icon: <Brain className="h-8 w-8 text-primary-600" />,
      title: "AI-Powered Questions",
      description: "Get role-specific interview questions generated by advanced AI."
    },
    {
      icon: <Mic className="h-8 w-8 text-primary-600" />,
      title: "Voice Interaction",
      description: "Practice with natural voice conversations using speech recognition."
    },
    {
      icon: <BarChart3 className="h-8 w-8 text-primary-600" />,
      title: "Detailed Analytics",
      description: "Receive comprehensive feedback on your interview performance."
    },
    {
      icon: <FileText className="h-8 w-8 text-primary-600" />,
      title: "PDF Reports",
      description: "Download professional reports to track your progress over time."
    }
  ];

  return (
    <section className="py-16 relative z-10">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ y: 50, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="text-center mb-12"
        >
          <h2 className="text-3xl font-bold text-gray-900 mb-4 font-heading calistoga-regular">
            Why Choose Our AI Interview Simulator?
          </h2>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Our advanced AI technology provides you with a realistic interview 
            experience tailored to your target role.
          </p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {features.map((feature, index) => (
            <motion.div
              key={index}
              initial={{ y: 50, opacity: 0 }}
              animate={{ y: 0, opacity: 1 }}
              transition={{ duration: 0.6, delay: 0.1 * index }}
            >
              <Card hover className="text-center h-full border-blue-200">
                <div className="flex justify-center mb-4">
                  {feature.icon}
                </div>
                <h3 className="text-xl font-semibold text-gray-900 mb-3">
                  {feature.title}
                </h3>
                <p className="text-gray-600">
                  {feature.description}
                </p>
              </Card>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default FeaturesSection;
